name: XLS to JSON

on:
  push:
    paths:
      - "data/rencontres/*.xlsx"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Get XLS file name
        id: getfile
        run: |
          FILE=$(jq -r '.head_commit.added[]?, .head_commit.modified[]? | select(endswith(".xlsx"))' <<< "$GITHUB_EVENT")
          echo "file=$FILE" >> $GITHUB_OUTPUT
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}


      - name: Convert XLS to JSON
        run: node scripts/matchs-xls-to-json.js ${{ steps.getfile.outputs.file }}
