name: Generate Resultats

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install      

      - name: Generate image        
        run: node scripts/matchs-div-to-image.js "https://abpecquencourt.fr/pages/resultats.2026.html" "docs/resultats.json" "../data/resultats/resultats.png"

      - name: Commit image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/resultats/resultats.png
          git diff --cached --quiet || git commit -m "chore: Ajout de l'image de la semaine"
          git push

      - name: Envoyer le mail
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Resultats généré"
          to: ${{ secrets.NOTIFY_EMAIL }}
          from: ABP WebSite Bot
          html_body: |
            <img src="https://abpecquencourt.fr/data/resultats/resultats.png" alt="Affiche des resultats" style="max-width:600px;" />